s_a[19] =
  " Agatti Island|Bingaram Island|Bitra Island|Chetlat Island|Kadmat Island|Kalpeni Island|Kavaratti Island|Kiltan Island|Lakshadweep Sea|Minicoy Island|North Island|South Island ";
s_a[20] =
  " Agar|Ajaigarh|Alirajpur|Amarpatan|Amarwada|Ambah|Anuppur|Arone|Ashoknagar|Ashta|Atner|Babaichichli|Badamalhera|Badarwsas|Badnagar|Badnawar|Badwani|Bagli|Baihar|Balaghat|Baldeogarh|Baldi|Bamori|Banda|Bandhavgarh|Bareli|Baroda|Barwaha|Barwani|Batkakhapa|Begamganj|Beohari|Berasia|Berchha|Betul|Bhainsdehi|Bhander|Bhanpura|Bhikangaon|Bhimpur|Bhind|Bhitarwar|Bhopal|Biaora|Bijadandi|Bijawar|Bijaypur|Bina|Birsa|Birsinghpur|Budhni|Burhanpur|Buxwaha|Chachaura|Chanderi|Chaurai|Chhapara|Chhatarpur|Chhindwara|Chicholi|Chitrangi|Churhat|Dabra|Damoh|Datia|Deori|Deosar|Depalpur|Dewas|Dhar|Dharampuri|Dindori|Gadarwara|Gairatganj|Ganjbasoda|Garoth|Ghansour|Ghatia|Ghatigaon|Ghorandogri|Ghughari|Gogaon|Gohad|Goharganj|Gopalganj|Gotegaon|Gourihar|Guna|Gunnore|Gwalior|Gyraspur|Hanumana|Harda|Harrai|Harsud|Hatta|Hoshangabad|Ichhawar|Indore|Isagarh|Itarsi|Jabalpur|Jabera|Jagdalpur|Jaisinghnagar|Jaithari|Jaitpur|Jaitwara|Jamai|Jaora|Jatara|Jawad|Jhabua|Jobat|Jora|Kakaiya|Kannod|Kannodi|Karanjia|Kareli|Karera|Karhal|Karpa|Kasrawad|Katangi|Katni|Keolari|Khachrod|Khajuraho|Khakner|Khalwa|Khandwa|Khaniadhana|Khargone|Khategaon|Khetia|Khilchipur|Khirkiya|Khurai|Kolaras|Kotma|Kukshi|Kundam|Kurwai|Kusmi|Laher|Lakhnadon|Lamta|Lanji|Lateri|Laundi|Maheshwar|Mahidpurcity|Maihar|Majhagwan|Majholi|Malhargarh|Manasa|Manawar|Mandla|Mandsaur|Manpur|Mauganj|Mawai|Mehgaon|Mhow|Morena|Multai|Mungaoli|Nagod|Nainpur|Narsingarh|Narsinghpur|Narwar|Nasrullaganj|Nateran|Neemuch|Niwari|Niwas|Nowgaon|Pachmarhi|Pandhana|Pandhurna|Panna|Parasia|Patan|Patera|Patharia|Pawai|Petlawad|Pichhore|Piparia|Pohari|Prabhapattan|Punasa|Pushprajgarh|Raghogarh|Raghunathpur|Rahatgarh|Raisen|Rajgarh|Rajpur|Ratlam|Rehli|Rewa|Sabalgarh|Sagar|Sailana|Sanwer|Sarangpur|Sardarpur|Satna|Saunsar|Sehore|Sendhwa|Seondha|Seoni|Seonimalwa|Shahdol|Shahnagar|Shahpur|Shajapur|Sheopur|Sheopurkalan|Shivpuri|Shujalpur|Sidhi|Sihora|Silwani|Singrauli|Sirmour|Sironj|Sitamau|Sohagpur|Sondhwa|Sonkatch|Susner|Tamia|Tarana|Tendukheda|Teonthar|Thandla|Tikamgarh|Timarani|Udaipura|Ujjain|Umaria|Umariapan|Vidisha|Vijayraghogarh|Waraseoni|Zhirnia ";
s_a[21] =
  " Achalpur|Aheri|Ahmednagar|Ahmedpur|Ajara|Akkalkot|Akola|Akole|Akot|Alibagh|Amagaon|Amalner|Ambad|Ambejogai|Amravati|Arjuni Merogaon|Arvi|Ashti|Atpadi|Aurangabad|Ausa|Babhulgaon|Balapur|Baramati|Barshi Takli|Barsi|Basmatnagar|Bassein|Beed|Bhadrawati|Bhamregadh|Bhandara|Bhir|Bhiwandi|Bhiwapur|Bhokar|Bhokardan|Bhoom|Bhor|Bhudargad|Bhusawal|Billoli|Brahmapuri|Buldhana|Butibori|Chalisgaon|Chamorshi|Chandgad|Chandrapur|Chandur|Chanwad|Chhikaldara|Chikhali|Chinchwad|Chiplun|Chopda|Chumur|Dahanu|Dapoli|Darwaha|Daryapur|Daund|Degloor|Delhi Tanda|Deogad|Deolgaonraja|Deori|Desaiganj|Dhadgaon|Dhanora|Dharani|Dhiwadi|Dhule|Dhulia|Digras|Dindori|Edalabad|Erandul|Etapalli|Gadhchiroli|Gadhinglaj|Gaganbavada|Gangakhed|Gangapur|Gevrai|Ghatanji|Golegaon|Gondia|Gondpipri|Goregaon|Guhagar|Hadgaon|Hatkangale|Hinganghat|Hingoli|Hingua|Igatpuri|Indapur|Islampur|Jalgaon|Jalna|Jamkhed|Jamner|Jath|Jawahar|Jintdor|Junnar|Kagal|Kaij|Kalamb|Kalamnuri|Kallam|Kalmeshwar|Kalwan|Kalyan|Kamptee|Kandhar|Kankavali|Kannad|Karad|Karjat|Karmala|Katol|Kavathemankal|Kedgaon|Khadakwasala|Khamgaon|Khed|Khopoli|Khultabad|Kinwat|Kolhapur|Kopargaon|Koregaon|Kudal|Kuhi|Kurkheda|Kusumba|Lakhandur|Langa|Latur|Lonar|Lonavala|Madangad|Madha|Mahabaleshwar|Mahad|Mahagaon|Mahasala|Mahaswad|Malegaon|Malgaon|Malgund|Malkapur|Malsuras|Malwan|Mancher|Mangalwedha|Mangaon|Mangrulpur|Manjalegaon|Manmad|Maregaon|Mehda|Mekhar|Mohadi|Mohol|Mokhada|Morshi|Mouda|Mukhed|Mul|Mumbai|Murbad|Murtizapur|Murud|Nagbhir|Nagpur|Nahavara |Nanded| Nandgaon|Nandnva|Nandurbar|Narkhed|Nashik|Navapur|Ner|Newasa|Nilanga|Niphad|Omerga|Osmanabad|Pachora|Paithan|Palghar|Pali|Pandharkawada|Pandharpur|Panhala|Paranda|Parbhani|Parner|Parola|Parseoni|Partur|Patan|Pathardi|Pathari|Patoda|Pauni|Peint|Pen|Phaltan|Pimpalner|Pirangut|Poladpur|Pune|Pusad|Pusegaon|Radhanagar|Rahuri|Raigad|Rajapur|Rajgurunagar|Rajura|Ralegaon|Ramtek|Ratnagiri|Raver|Risod|Roha|Sakarwadi|Sakoli|Sakri|Salekasa|Samudrapur|Sangamner|Sanganeshwar|Sangli|Sangola|Sanguem|Saoner|Saswad|Satana|Satara|Sawantwadi|Seloo|Shahada|Shahapur|Shahuwadi|Shevgaon|Shirala|Shirol|Shirpur|Shirur|Shirwal|Sholapur|Shri Rampur|Shrigonda|Shrivardhan|Sillod|Sinderwahi|Sindhudurg|Sindkheda|Sindkhedaraja|Sinnar|Sironcha|Soyegaon|Surgena|Talasari|Talegaon S.Ji Pant|Taloda|Tasgaon|Thane|Tirora|Tiwasa|Trimbak|Tuljapur|Tumsar|Udgir|Umarkhed|Umrane|Umrer|Urlikanchan|Vaduj|Velhe|Vengurla|Vijapur|Vita|Wada|Wai|Walchandnagar|Wani|Wardha|Warlydwarud|Warora|Washim|Wathar|Yavatmal|Yawal|Yeola|Yeotmal ";
s_a[22] =
  " Bishnupur|Chakpikarong|Chandel|Chattrik|Churachandpur|Imphal|Jiribam|Kakching|Kalapahar|Mao|Mulam|Parbung|Sadarhills|Saibom|Sempang|Senapati|Sochumer|Taloulong|Tamenglong|Thinghat|Thoubal|Ukhrul ";
s_a[23] =
  " Amlaren|Baghmara|Cherrapunjee|Dadengiri|Garo Hills|Jaintia Hills|Jowai|Khasi Hills|Khliehriat|Mariang|Mawkyrwat|Nongpoh|Nongstoin|Resubelpara|Ri Bhoi|Shillong|Tura|Williamnagar";
s_a[24] =
  " Aizawl|Champhai|Demagiri|Kolasib|Lawngtlai|Lunglei|Mamit|Saiha|Serchhip";
s_a[25] =
  " Dimapur|Jalukie|Kiphire|Kohima|Mokokchung|Mon|Phek|Tuensang|Wokha|Zunheboto ";
s_a[26] =
  " Anandapur|Angul|Anugul|Aska|Athgarh|Athmallik|Attabira|Bagdihi|Balangir|Balasore|Baleswar|Baliguda|Balugaon|Banaigarh|Bangiriposi|Barbil|Bargarh|Baripada|Barkot|Basta|Berhampur|Betanati|Bhadrak|Bhanjanagar|Bhawanipatna|Bhubaneswar|Birmaharajpur|Bisam Cuttack|Boriguma|Boudh|Buguda|Chandbali|Chhatrapur|Chhendipada|Cuttack|Daringbadi|Daspalla|Deodgarh|Deogarh|Dhanmandal|Dharamgarh|Dhenkanal|Digapahandi|Dunguripali|G. Udayagiri|Gajapati|Ganjam|Ghatgaon|Gudari|Gunupur|Hemgiri|Hindol|Jagatsinghapur|Jajpur|Jamankira|Jashipur|Jayapatna|Jeypur|Jharigan|Jharsuguda|Jujumura|Kalahandi|Kalimela|Kamakhyanagar|Kandhamal|Kantabhanji|Kantamal|Karanjia|Kashipur|Kendrapara|Kendujhar|Keonjhar|Khalikote|Khordha|Khurda|Komana|Koraput|Kotagarh|Kuchinda|Lahunipara|Laxmipur|M. Rampur|Malkangiri|Mathili|Mayurbhanj|Mohana|Motu|Nabarangapur|Naktideul|Nandapur|Narlaroad|Narsinghpur|Nayagarh|Nimapara|Nowparatan|Nowrangapur|Nuapada|Padampur|Paikamal|Palla Hara|Papadhandi|Parajang|Pardip|Parlakhemundi|Patnagarh|Pattamundai|Phiringia|Phulbani|Puri|Puruna Katak|R. Udayigiri|Rairakhol|Rairangpur|Rajgangpur|Rajkhariar|Rayagada|Rourkela|Sambalpur|Sohela|Sonapur|Soro|Subarnapur|Sunabeda|Sundergarh|Surada|T. Rampur|Talcher|Telkoi|Titlagarh|Tumudibandha|Udala|Umerkote ";
s_a[27] =
  " Bahur|Karaikal|Mahe|Pondicherry|Purnankuppam|Valudavur|Villianur|Yanam ";
s_a[28] =
  " Abohar|Ajnala|Amritsar|Balachaur|Barnala|Batala|Bathinda|Chandigarh|Dasua|Dinanagar|Faridkot|Fatehgarh Sahib|Fazilka|Ferozepur|Garhashanker|Goindwal|Gurdaspur|Guruharsahai|Hoshiarpur|Jagraon|Jalandhar|Jugial|Kapurthala|Kharar|Kotkapura|Ludhiana|Malaut|Malerkotla|Mansa|Moga|Muktasar|Nabha|Nakodar|Nangal|Nawanshahar|Nawanshahr|Pathankot|Patiala|Patti|Phagwara|Phillaur|Phulmandi|Quadian|Rajpura|Raman|Rayya|Ropar|Rupnagar|Samana|Samrala|Sangrur|Sardulgarh|Sarhind|SAS Nagar|Sultanpur Lodhi|Sunam|Tanda Urmar|Tarn Taran|Zira ";
s_a[29] =
  " Abu Road|Ahore|Ajmer|Aklera|Alwar|Amber|Amet|Anupgarh|Asind|Aspur|Atru|Bagidora|Bali|Bamanwas|Banera|Bansur|Banswara|Baran|Bari|Barisadri|Barmer|Baseri|Bassi|Baswa|Bayana|Beawar|Begun|Behror|Bhadra|Bharatpur|Bhilwara|Bhim|Bhinmal|Bikaner|Bilara|Bundi|Chhabra|Chhipaborad|Chirawa|Chittorgarh|Chohtan|Churu|Dantaramgarh|Dausa|Deedwana|Deeg|Degana|Deogarh|Deoli|Desuri|Dhariawad|Dholpur|Digod|Dudu|Dungarpur|Dungla|Fatehpur|Gangapur|Gangdhar|Gerhi|Ghatol|Girwa|Gogunda|Hanumangarh|Hindaun|Hindoli|Hurda|Jahazpur|Jaipur|Jaisalmer|Jalore|Jhalawar|Jhunjhunu|Jodhpur|Kaman|Kapasan|Karauli|Kekri|Keshoraipatan|Khandar|Kherwara|Khetri|Kishanganj|Kishangarh|Kishangarhbas|Kolayat|Kota|Kotputli|Kotra|Kotri|Kumbalgarh|Kushalgarh|Ladnun|Ladpura|Lalsot|Laxmangarh|Lunkaransar|Mahuwa|Malpura|Malvi|Mandal|Mandalgarh|Mandawar|Mangrol|Marwar-Jn|Merta|Nadbai|Nagaur|Nainwa|Nasirabad|Nathdwara|Nawa|Neem Ka Thana|Newai|Nimbahera|Nohar|Nokha|Onli|Osian|Pachpadara|Pachpahar|Padampur|Pali|Parbatsar|Phagi|Phalodi|Pilani|Pindwara|Pipalda|Pirawa|Pokaran|Pratapgarh|Raipur|Raisinghnagar|Rajgarh|Rajsamand|Ramganj Mandi|Ramgarh|Rashmi|Ratangarh|Reodar|Rupbas|Sadulshahar|Sagwara|Sahabad|Salumber|Sanchore|Sangaria|Sangod|Sapotra|Sarada|Sardarshahar|Sarwar|Sawai Madhopur|Shahapura|Sheo|Sheoganj|Shergarh|Sikar|Sirohi|Siwana|Sojat|Sri Dungargarh|Sri Ganganagar|Sri Karanpur|Sri Madhopur|Sujangarh|Taranagar|Thanaghazi|Tibbi|Tijara|Todaraisingh|Tonk|Udaipur|Udaipurwati|Uniayara|Vallabhnagar|Viratnagar ";
s_a[30] =
  " Barmiak|Be|Bhurtuk|Chhubakha|Chidam|Chubha|Chumikteng|Dentam|Dikchu|Dzongri|Gangtok|Gauzing|Gyalshing|Hema|Kerung|Lachen|Lachung|Lema|Lingtam|Lungthu|Mangan|Namchi|Namthang|Nanga|Nantang|Naya Bazar|Padamachen|Pakhyong|Pemayangtse|Phensang|Rangli|Rinchingpong|Sakyong|Samdong|Singtam|Siniolchu|Sombari|Soreng|Sosing|Tekhug|Temi|Tsetang|Tsomgo|Tumlong|Yangang|Yumtang ";
s_a[31] =
  " Ambasamudram|Anamali|Arakandanallur|Arantangi|Aravakurichi|Ariyalur|Arkonam|Arni|Aruppukottai|Attur|Avanashi|Batlagundu|Bhavani|Chengalpattu|Chengam|Chennai|Chidambaram|Chingleput|Coimbatore|Courtallam|Cuddalore|Cumbum|Denkanikoitah|Devakottai|Dharampuram|Dharmapuri|Dindigul|Erode|Gingee|Gobichettipalayam|Gudalur|Gudiyatham|Harur|Hosur|Jayamkondan|Kallkurichi|Kanchipuram|Kangayam|Kanyakumari|Karaikal|Karaikudi|Karur|Keeranur|Kodaikanal|Kodumudi|Kotagiri|Kovilpatti|Krishnagiri|Kulithalai|Kumbakonam|Kuzhithurai|Madurai|Madurantgam|Manamadurai|Manaparai|Mannargudi|Mayiladuthurai|Mayiladutjurai|Mettupalayam|Metturdam|Mudukulathur|Mulanur|Musiri|Nagapattinam|Nagarcoil|Namakkal|Nanguneri|Natham|Neyveli|Nilgiris|Oddanchatram|Omalpur|Ootacamund|Ooty|Orathanad|Palacode|Palani|Palladum|Papanasam|Paramakudi|Pattukottai|Perambalur|Perundurai|Pollachi|Polur|Pondicherry|Ponnamaravathi|Ponneri|Pudukkottai|Rajapalayam|Ramanathapuram|Rameshwaram|Ranipet|Rasipuram|Salem|Sankagiri|Sankaran|Sathiyamangalam|Sivaganga|Sivakasi|Sriperumpudur|Srivaikundam|Tenkasi|Thanjavur|Theni|Thirumanglam|Thiruraipoondi|Thoothukudi|Thuraiyure|Tindivanam|Tiruchendur|Tiruchengode|Tiruchirappalli|Tirunelvelli|Tirupathur|Tirupur|Tiruttani|Tiruvallur|Tiruvannamalai|Tiruvarur|Tiruvellore|Tiruvettipuram|Trichy|Tuticorin|Udumalpet|Ulundurpet|Usiliampatti|Uthangarai|Valapady|Valliyoor|Vaniyambadi|Vedasandur|Vellore|Velur|Vilathikulam|Villupuram|Virudhachalam|Virudhunagar|Wandiwash|Yercaud ";
s_a[32] =
  " Agartala|Ambasa|Bampurbari|Belonia|Dhalai|Dharam Nagar|Kailashahar|Kamal Krishnabari|Khopaiyapara|Khowai|Phuldungsei|Radha Kishore Pur|Tripura ";
s_a[33] =
  " Achhnera|Agra|Akbarpur|Aliganj|Aligarh|Allahabad|Ambedkar Nagar|Amethi|Amiliya|Amroha|Anola|Atrauli|Auraiya|Azamgarh|Baberu|Badaun|Baghpat|Bagpat|Baheri|Bahraich|Ballia|Balrampur|Banda|Bansdeeh|Bansgaon|Bansi|Barabanki|Bareilly|Basti|Bhadohi|Bharthana|Bharwari|Bhogaon|Bhognipur|Bidhuna|Bijnore|Bikapur|Bilari|Bilgram|Bilhaur|Bindki|Bisalpur|Bisauli|Biswan|Budaun|Budhana|Bulandshahar|Bulandshahr|Capianganj|Chakia|Chandauli|Charkhari|Chhata|Chhibramau|Chirgaon|Chitrakoot|Chunur|Dadri|Dalmau|Dataganj|Debai|Deoband|Deoria|Derapur|Dhampur|Domariyaganj|Dudhi|Etah|Etawah|Faizabad|Farrukhabad|Fatehpur|Firozabad|Garauth|Garhmukteshwar|Gautam Buddha Nagar|Ghatampur|Ghaziabad|Ghazipur|Ghosi|Gonda|Gorakhpur|Gunnaur|Haidergarh|Hamirpur|Hapur|Hardoi|Harraiya|Hasanganj|Hasanpur|Hathras|Jalalabad|Jalaun|Jalesar|Jansath|Jarar|Jasrana|Jaunpur|Jhansi|Jyotiba Phule Nagar|Kadipur|Kaimganj|Kairana|Kaisarganj|Kalpi|Kannauj|Kanpur|Karchhana|Karhal|Karvi|Kasganj|Kaushambi|Kerakat|Khaga|Khair|Khalilabad|Kheri|Konch|Kumaon|Kunda|Kushinagar|Lalganj|Lalitpur|Lucknow|Machlishahar|Maharajganj|Mahoba|Mainpuri|Malihabad|Mariyahu|Math|Mathura|Mau|Maudaha|Maunathbhanjan|Mauranipur|Mawana|Meerut|Mehraun|Meja|Mirzapur|Misrikh|Modinagar|Mohamdabad|Mohamdi|Moradabad|Musafirkhana|Muzaffarnagar|Nagina|Najibabad|Nakur|Nanpara|Naraini|Naugarh|Nawabganj|Nighasan|Noida|Orai|Padrauna|Pahasu|Patti|Pharenda|Phoolpur|Phulpur|Pilibhit|Pitamberpur|Powayan|Pratapgarh|Puranpur|Purwa|Raibareli|Rampur|Ramsanehi Ghat|Rasara|Rath|Robertsganj|Sadabad|Safipur|Sagri|Saharanpur|Sahaswan|Sahjahanpur|Saidpur|Salempur|Salon|Sambhal|Sandila|Sant Kabir Nagar|Sant Ravidas Nagar|Sardhana|Shahabad|Shahganj|Shahjahanpur|Shikohabad|Shravasti|Siddharthnagar|Sidhauli|Sikandra Rao|Sikandrabad|Sitapur|Siyana|Sonbhadra|Soraon|Sultanpur|Tanda|Tarabganj|Tilhar|Unnao|Utraula|Varanasi|Zamania";
s_a[34] =
  "Almora|Bageshwar|Bhatwari|Chakrata|Chamoli|Champawat|Dehradun|Deoprayag|Dharchula|Dunda|Haldwani|Haridwar|Joshimath|Karan Prayag|Kashipur|Khatima|Kichha|Lansdown|Munsiari|Mussoorie|Nainital|Pantnagar|Partapnagar|Pauri Garhwal|Pithoragarh|Purola|Rajgarh|Ranikhet|Roorkee|Rudraprayag|Tehri Garhwal|Udham Singh Nagar|Ukhimath|Uttarkashi";
s_a[35] =
  "Adra|Alipurduar|Amlagora|Arambagh|Asansol|Balurghat|Bankura|Bardhaman|Basirhat|Berhampur|Bethuadahari|Birbhum|Birpara|Bishanpur|Bolpur|Bongoan|Bulbulchandi|Burdwan|Calcutta|Canning|Champadanga|Contai|Cooch Behar|Daimond Harbour|Dalkhola|Dantan|Darjeeling|Dhaniakhali|Dhuliyan|Dinajpur|Dinhata|Durgapur|Gangajalghati|Gangarampur|Ghatal|Guskara|Habra|Haldia|Harirampur|Harishchandrapur|Hooghly|Howrah|Islampur|Jagatballavpur|Jalpaiguri|Jhalda|Jhargram|Kakdwip|Kalchini|Kalimpong|Kalna|Kandi|Karimpur|Katwa|Kharagpur|Khatra|Krishnanagar|Mal Bazar|Malda|Manbazar|Mathabhanga|Medinipur|Mekhliganj|Mirzapur|Murshidabad|Nadia|Nagarakata|Nalhati|Nayagarh|Parganas|Purulia|Raiganj|Rampur Hat|Ranaghat|Seharabazar|Siliguri|Suri|Takipur|Tamluk";
